name: Check environment

on:
  push:
    branches:
      - main
      - dev/thien
  pull_request:
    branches:
      - main
      - dev/thien
  workflow_dispatch:

jobs:
  test_environment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.0"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Test if we can import train.py, test_multiple_checkpoints.py, and test_with_model_soups.py
        run: |
          uv run python --version
          uv run python train.py --help
          uv run python run_test_multiple_checkpoints.py --help
          uv run python run_test_with_model_soups.py --help
