name: Check imports

on:
  push:
    branches:
      - main
      - dev/thien
      - dev/khang
  pull_request:
    branches:
      - main
      - dev/thien
      - dev/khang
  workflow_dispatch:

jobs:
  check_imports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.0"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Check imports
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          uv run python .github/workflow/check_imports.py --src_path soups
