name: Lint with ruff

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "soups/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "soups/**"
  workflow_dispatch:

jobs:
  lint_with_ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.13"
          python-version: "3.10"
          enable-cache: true

      - name: Lint with ruff
        run: |
          uv run ruff check --output-format=github soups
